# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
  adapter: postgresql
  database: csci
  pool: 5
  timeout: 5000
  username: postgres
  password: a
  
test:
  adapter: postgresql
  database: csci
  pool: 5
  timeout: 5000
  username: postgres
  password: a

production:
  adapter: postgresql
  database: csci
  pool: 5
  timeout: 5000
  username: postgres
  password: a